microsoft/vscode-docs-authoring

- authoring-extension/src/helper/utility.ts
No longer using Gauntlet logging service so moving error messages to table validator
> Update table warning messages

- authoring-extension/package-lock.json
- authoring-extension/package.json
Update package/package-lock.json files to resolve hoek alert.
> GitHub vulnerability alert for hoek < 5.0.3

- docs-authoring-pack/readme.md
Attempt to fix what was showing in the details for this extension in the VSCode marketplace.
> Fix readme header syntax.

- docs-markdown/package-lock.json
- docs-markdown/package.json
- docs-preview/package-lock.json
- docs-preview/package.json
Remove vulnerable dependency `hoek: 2.16.3`
> Update vscode version to avoid vulnerable dependency

- docs-markdown/src/helper/utility.ts
1. Removed unnecessary require (os module)
2. Removed conditional platform logic for slash syntax
3. Simplified path logic by using path.parse and path.relative methods
4. Update snippet links to follow CommonMark syntax
> Update snippet logic

- docs-markdown/src/controllers/quick-pick-menu-controller.ts
See https://ceapex.visualstudio.com/Engineering/_workitems/edit/19982.
1. Added conditional check for the "Preview" function in the quick pick snippet.
2. Small refactor of code to avoid code repetition - pulled out extension check into a shared function.
> Conditionally add preview entry to quick pick.

- docs-preview/media/markdown.css
1. Add properties for caution, tip and important alert types.
2. Add properties for light themes.
> Update alert styles

- docs-markdown/package.json
- docs-markdown/schema/toc.schema.json
See https://ceapex.visualstudio.com/Engineering/_workitems/edit/23437.
1. Add TOC schema for YAML validation.
2. Add yamlValidation configuration for the RedHat plugin to consume at startup.
Testing this requires installation of the Red Hat extension: https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml#overview
> Add configuration for yaml validation schema.

- docs-markdown/package.json
Updating authoring menu title to follow standard.
> Standardize title

- docs-article-templates/package.json
- docs-article-templates/src/controllers/quick-pick-controller.ts
- docs-article-templates/src/controllers/template-controller.ts
- docs-article-templates/src/helper/github.ts
1. Call showTemplates function directly from downloadRepo; only launches on a successful download.
2. Specifiy functions in imports.
3. Remove console output.
4. Remove timeout.
> Improve flow

- docs-preview/package-lock.json
- docs-preview/package.json
- docs-preview/src/provider.ts
> Display plain text for xref

- docs-article-templates/package-lock.json
- docs-markdown/package-lock.json
- docs-preview/package-lock.json
Fixes security vulnerabilities in packagelock.json files.
> Update url-parse dependency

- docs-article-templates/CHANGELOG.md
- docs-article-templates/package-lock.json
- docs-article-templates/package.json
1. Remove telemetry dependency to resolve [https://github.com/Microsoft/vscode-docs-authoring/issues/100](https://github.com/Microsoft/vscode-docs-authoring/issues/100)
2. Update command name
> Command name update and remove unused dependency

- docs-markdown/changelog.md
- docs-markdown/package.json
- docs-markdown/src/controllers/bookmark-controller.ts
1. Updated quickpick logic to add items to a quickpick array using labels (heading title) and detail (blank space to help with rendering).
2. Removed unnecessary else statements.
3. Updated constants in both insertBookmarkInternal and insertBookmarkExternal functions for consistency.
> Fix bookmark/heading quickpick results

- docs-preview/src/provider.ts
- docs-preview/src/xref/xrefInfo.ts
- docs-preview/src/xref/xrefResolver.ts
This is the long term solution for xref service preview behavior.
> Integrate xref service to resolve xref syntax

- docs-markdown/package-lock.json
- docs-markdown/package.json
Update vscode version (package.json) and additional dependencies (package.lock).
> Fix event-stream vulnerability

- docs-markdown/src/controllers/media-controller.ts
No need to add the https:// prefill.
> Remove web/external link prefill

- docs-article-templates/package-lock.json
- docs-article-templates/package.json
- docs-markdown/package-lock.json
- docs-markdown/package.json
- docs-preview/package-lock.json
- docs-preview/package.json
Ran 'npm audit fix' to address vulnerabilities in dependent packages.
> Fix security vulnerabilities

- docs-markdown/package-lock.json
- docs-markdown/package.json
- docs-markdown/src/controllers/quick-pick-menu-controller.ts
- docs-markdown/src/extension.ts
1. Change when clause for applyCleanup command
2. Add js-yaml as dependency
3. Register commands
> Feedback - Do not merge

- docs-article-templates/src/helper/unit-builder.ts
Making `interactive-tutorial` the default for `ms.topic` since that's the only option for Learn content
> Set default value for ms.topic in Learn unit yml

- docs-article-templates/package.json
- docs-article-templates/src/helper/module-builder.ts
- docs-article-templates/src/helper/user-settings.ts
1. Remove settings from package.json
2. Remove settings from user-settings
3. Change settings values to placeholders in module-builder.ts
> Remove default metadata values

- docs-markdown/README.md
- docs-markdown/changelog.md
- docs-markdown/package.json
- docs-markdown/src/controllers/cleanup-controller.ts
- docs-markdown/src/controllers/master-redirect-controller.ts
- docs-markdown/src/extension.ts
- Fixed progress indicator to no longer output to the console. Now only displaying for Progress report/indicator.
- Fixed issue with git status showing change but no diff. There was line ending/ white space differences. Now checking if null or white space before updating.
> Cleanup Fixes for Progress indicator

- docs-preview/README.md
- docs-preview/changelog.md
1. Update changelog and readme.
> Prep for release

- docs-markdown/changelog.md
- docs-markdown/package-lock.json
- docs-markdown/package.json
- docs-markdown/src/controllers/alert-controller.ts
- docs-markdown/src/controllers/bold-controller.ts
- docs-markdown/src/controllers/bookmark-controller.ts
- docs-markdown/src/controllers/cleanup-controller.ts
- docs-markdown/src/controllers/code-controller.ts
- docs-markdown/src/controllers/include-controller.ts
- docs-markdown/src/controllers/italic-controller.ts
- docs-markdown/src/controllers/list-controller.ts
- docs-markdown/src/controllers/master-redirect-controller.ts
- docs-markdown/src/controllers/media-controller.ts
- docs-markdown/src/controllers/preview-controller.ts
- docs-markdown/src/controllers/snippet-controller.ts
- docs-markdown/src/controllers/table-controller.ts
- docs-markdown/src/controllers/template-controller.ts
- docs-markdown/src/extension.ts
- docs-markdown/src/helper/telemetry.ts
1. Add telemetry events
2. Small tslint fixes
> Add telemetry to docs-markdown

- docs-article-templates/README.md
- docs-markdown/README.md
- docs-preview/README.md
- docs-yaml/README.md
- Add build status to each of the extensions README
> Added dev ops badge to readme.

- docs-yaml/CHANGELOG.md
- docs-yaml/package-lock.json
- docs-yaml/package.json
- docs-yaml/src/extension.ts
- docs-yaml/src/helper/telemetry.ts
- docs-yaml/src/yaml-support/yaml-schema.ts
- docs-yaml/src/yaml-support/yaml-snippet.ts
1. Add telemetry helper
2. Add calls to pull mime/topic type, schema errors and missing extension dependency.
3. Update extension version and changelog
> Adding telemetry to docs-yaml

- docs-markdown/changelog.md
- docs-markdown/package-lock.json
- docs-markdown/package.json
- docs-markdown/src/constants/docs-code-languages.ts
- docs-markdown/src/controllers/code-controller.ts
1. Remove "none" as an option
2. Add following text as placeholder: "Select a programming language (required)"
> Update fenced code UI

- docs-markdown/changelog.md
> Docs-markdown update changelog

- docs-markdown/changelog.md
- docs-preview/changelog.md
> Preview release

- docs-article-templates/src/controllers/quick-pick-controller.ts
- docs-article-templates/src/extension.ts
- docs-article-templates/src/helper/common.ts
- docs-article-templates/src/helper/github.ts
- docs-article-templates/src/helper/module-builder.ts
- docs-article-templates/src/helper/unit-builder.ts
- docs-article-templates/src/strings.ts
1. Added getRepoName, sendTelemetryData and showStatusMessage functions.
2. Each step will be logged with a timestamp.
3. Additional error-handling.
4. Named imports in common.
5. Added log messages to strings.ts.
> Add additional logging

- docs-markdown/package.json
- docs-markdown/src/controllers/quick-pick-menu-controller.ts
- docs-markdown/src/controllers/yaml-controller.ts
1. Add expandable parent node functionality.
2. Update quickpick and command palette with new command.
3. Move yaml entry content to constants, add a scalar per line and remove line breaks (account for indentation).
4. Update logic to check for cursor position.
> YAML parent node

- docs-markdown/markdownlint-custom-rules/common.js
> Add no-loc extension regex for custom lint rules

- docs-markdown/src/controllers/yaml-controller.ts
Remove maintainContext and items.
> Update TOC entry optional attributes

- docs-markdown/package-lock.json
- docs-markdown/package.json
- docs-markdown/src/controllers/lint-config-controller.ts
- docs-markdown/src/extension.ts
https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md025---multiple-top-level-headings-in-the-same-document
> Fix multiple top level headings lint error

- docs-metadata/package-lock.json
- docs-metadata/package.json
Updating display name to follow authoring pack convention.
> Update display name

- docs-preview/changelog.md
- docs-preview/media/alert-styles.css
- docs-preview/media/styles.css
- docs-preview/media/wrapper.js
- docs-preview/package.json
Fixed bug where user hover causes glitching styles.
> Fixed bug where user hover causes glitching styles.

- docs-markdown/src/helper/common.ts
Addresses issue [294](https://github.com/microsoft/vscode-docs-authoring/issues/294)
> Do not show output window by default

- docs-preview/media/next-step-action.js
- docs-preview/package.json
Add preview support for next step action button
> Preview next step action button

- docs-preview/media/single-selector.js
- docs-preview/media/styles.css
- docs-preview/package.json
> Single selector support

- docs-yaml/CHANGELOG.md
- docs-yaml/schemas/toc.schema.json
Not keyword caused schema errors in toc nodes with optional attributes.
> Fix yaml toc error

- docs-markdown/changelog.md
- docs-markdown/package.json
- docs-markdown/src/controllers/image-controller.ts
- docs-markdown/src/controllers/quick-pick-menu-controller.ts
Added standard markdown image syntax to quickpick.
> Added standard markdown image syntax to quickpick.

- docs-markdown/markdownlint-custom-rules/image.js
- docs-markdown/markdownlint-custom-rules/schemas.js
- docs-markdown/markdownlint-custom-rules/strings.js
1. Add function to pull data from an online schema.
2. Update attribute and type checks to use schema data.
3. Add schema file to store urls.
3. Add logging message.
> Update image linting

- docs-markdown/markdownlint-custom-rules/common.js
- docs-markdown/markdownlint-custom-rules/no-loc.js
- docs-markdown/markdownlint-custom-rules/strings.js
Fixed linting rule for no-loc quotes and added new rules for double quotes, allowed attributes, and required text attribute.
> Fixed linting rule for no-loc and added additional new rules.

- docs-markdown/changelog.md
- docs-markdown/package-lock.json
- docs-markdown/package.json
- Linting updates
- Security fixes
> December 6th release

- docs-markdown/src/helper/rows-columns.ts
1. Added checkForRow function to ensure cursor is in a valid row.
2. Added insertColumn function to store editor code for reuse.
3. Combined duplicated regex.
> Update row and column checks

- docs-markdown/changelog.md
- docs-markdown/package-lock.json
- docs-markdown/package.json
- docs-markdown/src/controllers/media-controller.ts
Fix for issue [376](https://github.com/microsoft/vscode-docs-authoring/issues/376)
> Fix alt text bug in macOS

- docs-markdown/package.json
update settings to output coverage report in summary and HTML for all `src` files
> Jest coverage report

- docs-markdown/src/helper/ui.ts
#440 Issue tracking for Insert Image command not found. Small bug was found after investigating, although we have moved to a different type of image insert, we did not update the ui button on the toolbar.
> Fixed issue with inserting image.

- docs-preview/.gitignore
- docs-preview/changelog.md
- docs-preview/media/wrapper.js
- docs-preview/package-lock.json
- docs-preview/package.json
- docs-preview/src/seo/seoHelpers.ts
> Release03182020

- docs-preview/README.md
> Fix demo link

- docs-markdown/changelog.md
- docs-markdown/package-lock.json
- docs-markdown/package.json
- docs-markdown/src/test/runTest.ts
- docs-markdown/src/test/suite/index-coverage.ts
Added mocha-junit-report to Azure DevOps
> Added JUnit coverage reporter

- docs-authoring-pack/CHANGELOG.md
- docs-authoring-pack/package.json
> Update Docs Authoring Pack Readme release

- docs-markdown/package.json
- docs-markdown/src/test/suite/controllers/alert-controller.test.ts
Added pre-push hook for linting
> Added pre-push hook for linting

- docs-preview/src/helper/telemetry.ts
- docs-preview/src/markdown-extensions/codesnippet.ts
- docs-preview/src/markdown-extensions/column.ts
- docs-preview/src/markdown-extensions/container.ts
- docs-preview/src/markdown-extensions/div.ts
- docs-preview/src/markdown-extensions/image.ts
- docs-preview/src/markdown-extensions/includes.ts
- docs-preview/src/markdown-extensions/row.ts
- docs-preview/src/markdown-extensions/video.ts
This PR fixes TSLint errors in docs-preview helper and extension files.  Unused code was also removed.
> TSLint: Fix linting errors in docs-preview helper and extension files

- docs-images/.vscodeignore
- docs-images/package.json
- docs-images/webpack.config.js
178627 fix docs images. Issue with loading extension for node_modules.
> 178627 fix docs images

- docs-preview/changelog.md
- docs-preview/package-lock.json
- docs-preview/package.json
- docs-preview/src/extension.ts
- docs-preview/src/markdown-extensions/image.ts
- Update regex capture groups
- Add conditional for matches
- Bump version and update changelog
> Fix complex image long description bug

- docs-metadata/src/controllers/extract-controller.ts
- docs-metadata/src/extension.ts
Resolves linting issues in extract-controller.ts and extension.ts
> TSLint fixes

- docs-markdown/changelog.md
- docs-markdown/src/controllers/code-controller.ts
- docs-markdown/src/controllers/quick-pick-menu-controller.ts
- docs-markdown/src/test/data/repo/articles/code.md
- docs-markdown/src/test/suite/controllers/code-controller.test.ts
- docs-markdown/src/test/suite/controllers/moniker-controller.test.ts
solved #546   &&  added unit test coverage: code-controller
> Added Moniker to quick-pick-menu-controller.ts

- docs-preview/src/extension.ts
- docs-preview/src/seo/docFxTypes.ts
- docs-preview/src/seo/seoHelpers.ts
- docs-preview/src/seo/seoPreview.ts
Added logic for getting breadcrumbs in Search Results Preview.
> Added logic for getting breadcrumbs in Search Results Preview.

- docs-markdown/changelog.md
- docs-markdown/package.json
- docs-preview/changelog.md
- docs-preview/package.json
- docs-markdown production release version 0.2.67
- docs-preview production release version 0.3.48
> Production Release for docs-markdown and docs-preview

- docs-preview/changelog.md
- docs-preview/package.json
Production release version 0.3.49
> docs-preview Production release version 0.3.49

- docs-markdown/src/test/suite/controllers/alert-controller.test.ts
- docs-markdown/src/test/suite/controllers/bookmark-controller.test.ts
- docs-markdown/src/test/suite/controllers/code-controller.test.ts
- docs-markdown/src/test/suite/controllers/include-controller.test.ts
- docs-markdown/src/test/suite/controllers/moniker-controller.test.ts
- docs-markdown/src/test/suite/index-coverage.ts
- docs-markdown/src/test/suite/index.ts
- docs-markdown/src/test/test.common/common.ts
Updated sleep time and test timeout.
> Updated sleep time and test timeout.

- docs-markdown/src/controllers/include-controller.ts
- docs-markdown/src/controllers/moniker-controller.ts
- docs-markdown/src/helper/common.ts
- docs-markdown/src/test/data/repo/includes/1.md
- docs-markdown/src/test/data/repo/includes/2.md
- docs-markdown/src/test/data/repo/includes/3.md
- docs-markdown/src/test/suite/controllers/include-controller.test.ts
- docs-markdown/src/test/suite/controllers/moniker-controller.test.ts
- docs-markdown/src/test/test.common/common.ts
Updated sleep time and now awaiting some insert content calls.
> Updated sleep time and now awaiting some insert content calls.

- docs-markdown/src/controllers/code-controller.ts
- docs-markdown/src/helper/format-logic-manager.ts
- docs-markdown/src/test/suite/controllers/code-controller.test.ts
- docs-markdown/src/test/suite/index-coverage.ts
- docs-markdown/src/test/suite/index.ts
Updated formatCode to await and increased timeout on tests
> Updated formatCode to await and increased timeout on tests

- docs-yaml/src/extension.ts
- docs-yaml/src/test/extension.test.ts
- docs-yaml/src/yaml-support/yaml-schem-Holder.ts
- docs-yaml/src/yaml-support/yaml-schema.ts
- docs-yaml/src/yaml-support/yaml-util.ts
> TSLint fixes in docs-yaml

- docs-markdown/src/controllers/cleanup/capitalizationOfMetadata.ts
- docs-markdown/src/controllers/cleanup/cleanup-controller.ts
- docs-markdown/src/controllers/cleanup/handleSingleValuedMetadata.ts
- docs-markdown/src/controllers/cleanup/microsoftLinks.ts
- docs-markdown/src/controllers/cleanup/removeEmptyMetadata.ts
- docs-markdown/src/controllers/cleanup/runAll.ts
- docs-markdown/src/controllers/cleanup/utilities.ts
- docs-markdown/src/test/data/repo/articles/docs-markdown.md
- docs-markdown/src/test/suite/controllers/cleanup/cleanup-controller.test.ts
- docs-markdown/src/test/suite/controllers/cleanup/microsoftLinks.test.ts
- docs-markdown/src/test/test.common/common.ts
Added unit tests for cleanup-controller.ts
> Added unit tests for cleanup-controller.ts

- docs-article-templates/package.json
> Update activation events

- docs-markdown/changelog.md
- docs-markdown/src/test/suite/controllers/cleanup/cleanup-controller.test.ts
- docs-markdown/src/test/suite/controllers/include-controller.test.ts
* update include-controller.test - add tests for Darwin
* update cleanup-controller.test - reuse stubs
> 🐛 fixes for tests

- docs-markdown/README.md
- docs-markdown/changelog.md
- docs-markdown/package.json
Updated package.json version and changelog.
> docs-markdown: Production Release 0.2.69

- docs-markdown/src/controllers/image-controller.ts
- docs-markdown/src/test/data/repo/articles/image-controller6.md
- docs-markdown/src/test/suite/controllers/image-controller.test.ts
- docs-markdown/src/test/suite/controllers/italic-controller.test.ts
- docs-markdown/tslint.json
1. Add support for clickable images
2. Fix linting errors in italics test
> Add support for clickable images

- docs-preview/changelog.md
- docs-preview/package.json
Updated package.json and changelog.
> Production Release 0.3.50 docs-preview

- docs-markdown/changelog.md
- docs-markdown/package.json
- docs-markdown/src/controllers/image-controller.ts
1. Clickable images
2. Master redirect updates
> Docs-markdown: Production release 

- docs-markdown/src/controllers/link-controller.ts
- docs-markdown/src/test/suite/controllers/link-controller.test.ts
- Ignore changes that simply remove leading `./`
- Fix reporting
- Make cancellable
- Increment progress
- File names, not full UNC paths
> Improvements to the "collapse relative links in folder" experience

- docs-markdown/changelog.md
- docs-markdown/package.json
updated change log and package.json.
> docs-markdown Production release 0.2.71

- docs-markdown/src/test/suite/controllers/quick-pick-menu-controller.test.ts
- docs-markdown/src/test/suite/controllers/table-controller.test.ts
Removing telemetry error below:
**quick-pick-menu-controller.test.ts**
- Add telemetry import
- Global telemetry hook
- Remove duplicate restore
**table-controller.test.ts**
- Global telemetry hooks
> Update unit tests

- docs-linting/changelog.md
- docs-linting/package.json
docs-linting Production release for schema linting
> docs-linting Production release for schema linting

- docs-markdown/changelog.md
- docs-markdown/package.json
- docs-preview/changelog.md
- docs-preview/package.json
Updated changelog and package.json
> docs-markdown and docs-preview production deployment

- docs-markdown/src/helper/common.ts
- docs-markdown/src/test/data/repo/articles/common.md
- docs-markdown/src/test/suite/helper/common.test.ts
Added unit tests for common.ts
> Added unit tests for common.ts

- docs-markdown/package.json
- docs-markdown/src/controllers/image-controller.ts
- docs-markdown/src/extension.ts
- docs-markdown/src/helper/AllowList.ts
- docs-markdown/src/helper/Auth.ts
- docs-markdown/src/helper/metadata-completion.ts
- docs-markdown/src/helper/triple-colon-extensions.ts
- docs-markdown/src/helper/utility.ts
- docs-markdown/src/test/data/repo/articles/metadata-completion.md
- docs-markdown/src/test/suite/controllers/image-controller.test.ts
- docs-markdown/src/test/suite/helper/AllowList.test.ts
- docs-markdown/src/test/suite/helper/Auth.test.ts
- docs-markdown/src/test/suite/helper/metadata-completion.test.ts
- docs-markdown/src/test/test.common/common.ts
Added metadata completion provider for auto-complete. Adding auto-complete on metadata front-matter values for ms.prod, ms.service, ms.technology, and ms.subservice.
> Auto-Complete for front-matter metadata

- docs-markdown/changelog.md
- docs-markdown/package.json
Added changelog and updated package.json. Changes include:
- Add list-controller tests
- Added auto-complete for ms.prod, ms.service, ms.subservice, and ms.technology.
> docs-markdown production release for version 0.2.76

- docs-markdown/src/controllers/yaml/createEntry.ts
- docs-markdown/src/controllers/yaml/createParentNode.ts
- docs-markdown/src/helper/common.ts
- docs-markdown/src/test/data/repo/articles/yaml-controller2.yml
- docs-markdown/src/test/data/repo/articles/yaml-controller3.yml
- docs-markdown/src/test/data/repo/articles/yaml-controller7.yml
- docs-markdown/src/test/suite/controllers/yaml-controller.test.ts
- docs-markdown/src/test/suite/index.ts
Fixed indent on TOC and added unit tests.
> Fixed indent on TOC and added unit tests.

- docs-markdown/package.json
- docs-markdown/src/controllers/cleanup/cleanup-controller.ts
- docs-markdown/src/controllers/cleanup/devlangsInCodeBlocks.ts
- docs-markdown/src/controllers/cleanup/utilities.ts
- docs-markdown/src/test/suite/controllers/cleanup/devlangsInCodeBlocks.test.ts
- docs-markdown/src/test/suite/controllers/quick-pick-menu-controller.test.ts
[AB#235780](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/235780)
> Cleanup script for bad devlangs in code blocks

- docs-preview/media/alert-styles.js
> Markdown Preview: Alert fix

- docs-markdown/changelog.md
- docs-markdown/src/test/suite/controllers/cleanup/remove-unused-assets-controller.test.ts
Resolves issue #495 
Open to suggestions for improvement!
> Unit test coverage for remove-unused-assets-controller

- docs-preview/package.json
- docs-preview/src/extension.ts
- docs-preview/src/markdown-extensions/codesnippet.ts
Added command to refresh the codesnippet cache.
[AB#277805](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/277805)
> Added command to refresh the codesnippet cache.

- docs-preview/media/styles.css
Added codesnippet styles for transparent background.
[AB#277797](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/277797)
> Added codesnippet styles for transparent background.

- docs-markdown/package.json
- docs-markdown/src/extension.ts
- docs-markdown/src/helper/AllowList.ts
- docs-markdown/src/helper/metadata.ts
- docs-markdown/src/test/suite/helper/AllowList.test.ts
Added proxy to allowlist. And removed config values that were for Allowlist API.
[AB#279111](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/279111)
> Added proxy to allowlist.

- docs-preview/changelog.md
- docs-preview/package.json
Updated changelog and incremented package.json version.
> docs-preview production release 0.3.55

- packages/docs-markdown/changelog.md
- packages/docs-markdown/src/helper/triple-colon-extensions.ts
- packages/docs-markdown/src/test/suite/helper/triple-colon-extensions.test.ts
Added triple colon code snippet to auto-complete.
[AB#286428](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/286428)
> Added triple colon code snippet to auto-complete.

- packages/docs-markdown/package.json
Updated package.json to release production version of docs-markdown
> docs-markdown production release 0.2.80

- packages/docs-markdown/src/controllers/no-loc-controller.ts
- packages/docs-markdown/src/test/data/repo/articles/no-loc-controller.md
- packages/docs-markdown/src/test/suite/controllers/no-loc-controller.test.ts
- packages/docs-markdown/src/test/suite/index-coverage.ts
- packages/docs-markdown/src/test/test.common/common.ts
Added no-loc unit tests.
[AB#179030](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/179030)
> Added no-loc unit tests.

- packages/docs-markdown-to-mail/changelog.md
- packages/docs-markdown-to-mail/src/controllers/mail-controller.ts
[AB#298433](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/298433)
> Add support for relative links

- packages/docs-markdown-to-mail/src/controllers/mail-controller.ts
- packages/docs-markdown-to-mail/src/markdown-extensions/column.ts
- packages/docs-markdown-to-mail/src/markdown-extensions/row.ts
[AB#298436](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/298436)
> Mailer: Support for rows and columns

- packages/docs-markdown/changelog.md
- packages/docs-markdown/package.json
- packages/docs-markdown/src/controllers/quick-pick-menu-controller.ts
- packages/docs-markdown/src/controllers/validation-controller.ts
- packages/docs-markdown/src/extension.ts
- packages/docs-markdown/src/helper/common.ts
- packages/docs-markdown/src/test/suite/controllers/quick-pick-menu-controller.test.ts
- packages/docs-markdown/src/test/suite/controllers/validation-controller.test.ts
- packages/docs-markdown/src/test/suite/helper/metadata-completion.test.ts
- packages/docs-markdown/src/test/test.common/common.ts
[AB#288438](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/288438)
> Add docs validation entrance to docs markdown extension

- packages/docs-markdown-to-mail/media/alert-styles.css
- packages/docs-markdown-to-mail/media/site-ltr.css
- packages/docs-markdown-to-mail/src/controllers/mail-controller.ts
[AB#298435](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/298435)
> Mailer: Add support for alerts

- packages/docs-markdown/src/helper/highlight-langs.ts
Updated with AL - the programming language for Dynamics 365 Business Central. Thanks!
> Update with AL, programming language

- packages/docs-markdown/src/test/suite/controllers/quick-pick-menu-controller.test.ts
- packages/docs-markdown/src/test/suite/controllers/validation-controller.test.ts
- packages/docs-markdown/src/test/suite/helper/metadata-completion.test.ts
- packages/docs-markdown/src/test/test.common/common.ts
- Fixed Extension Context type.
- Commented unit test that was breaking other unit tests on docs-markdown.
> commented unit test and fixed context.

- packages/docs-metadata/package.json
Reverts microsoft/vscode-docs-authoring#797
> Revert "Delete install.Lock"

- packages/docs-markdown/src/test/suite/helper/metadata.test.ts
Fixed unit test for configuration setup needed on metadata unit tests.
> Fixed build for unit tests on metadata nag.

- packages/docs-article-templates/package.json
- packages/docs-article-templates/src/controllers/template-controller.ts
- packages/docs-article-templates/src/helper/user-settings.ts
- packages/docs-article-templates/src/test/suite/extension.test.ts
- yarn.lock
[AB#365811](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/365811)
> 365811 friendly name repo specific

- packages/docs-markdown/src/controllers/cleanup/addPeriodsToAlt.ts
- packages/docs-markdown/src/controllers/cleanup/cleanup-controller.ts
- packages/docs-markdown/src/controllers/cleanup/utilities.ts
- packages/docs-markdown/src/test/suite/controllers/cleanup/addPeriodsToAlt.test.ts
- Added period to alt text command to cleanup quick pick menu.
- Added unit tests for period to alt text command.
AB#193989
> Added period to alt text command to cleanup quick pick menu.

- packages/docs-markdown/src/controllers/cleanup/devlangsInCodeBlocks.ts
- packages/docs-markdown/src/test/suite/controllers/cleanup/devlangsInCodeBlocks.test.ts
- Fixed devlang regex for lowercasing and fixing language paramters
AB#381113
> Fixed devlang regex for lowercasing and fixing language paramters

- packages/docs-markdown/src/controllers/cleanup/cleanup-controller.ts
- Added command to cleanup for period to alt text.
> Added command to cleanup for period to alt text.

- packages/docs-markdown/changelog.md
- packages/docs-markdown/package.json
docs-markdown production release 0.2.85
> docs-markdown production release 0.2.85

- packages/docs-markdown/src/controllers/cleanup/addPeriodsToAlt.ts
- packages/docs-markdown/src/test/suite/controllers/cleanup/addPeriodsToAlt.test.ts
[AB#405848](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/405848)
[AB#405816](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/405816)
> Support alt text ending with quotes and ignore whitespace

- packages/docs-markdown/src/controllers/cleanup/remove-unused-assets-controller.ts
- packages/docs-markdown/src/controllers/media-controller.ts
- packages/docs-markdown/src/helper/common.ts
- packages/docs-markdown/src/test/data/repo/articles/yml-title.yml
- packages/docs-markdown/src/test/suite/helper/common.test.ts
[AB#417410](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/417410)
> Support linking to YAML files in Docs Markdown

- packages/docs-markdown/src/controllers/cleanup/addPeriodsToAlt.ts
- packages/docs-markdown/src/test/suite/controllers/cleanup/addPeriodsToAlt.test.ts
[AB#405820](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/405820)
> 405820 lightbox alt text

- packages/docs-markdown/src/controllers/cleanup/addPeriodsToAlt.ts
- packages/docs-markdown/src/test/suite/controllers/cleanup/addPeriodsToAlt.test.ts
[AB#405822](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/405822)
> Update alt text regex

- packages/docs-markdown/package.json
- packages/docs-markdown/src/controllers/yaml/showTOCQuickPick.ts
- packages/docs-markdown/src/helper/getHeader.ts
- packages/docs-markdown/src/test/suite/controllers/yaml-controller.test.ts
- packages/docs-markdown/src/test/suite/helper/getHeader.test.ts
- yarn.lock
[AB#417920](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/417920)
> TOC entry bugfix and refactor

- packages/docs-markdown/package.json
- packages/docs-markdown/src/controllers/yaml/showTOCQuickPick.ts
- packages/docs-markdown/src/helper/getHeader.ts
- packages/docs-markdown/src/test/data/repo/articles/bookmark-2.md
- packages/docs-markdown/src/test/suite/helper/getHeader.test.ts
- yarn.lock
[AB#435572](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/435572)
> Fix heading command

- packages/docs-markdown/src/controllers/cleanup/microsoftLinks.ts
- packages/docs-markdown/src/controllers/links/linkToDocsPageByUrl.ts
- packages/docs-markdown/src/controllers/media-controller.ts
CodeQL rule suppression for certain lines of code
> CodeQL rule suppression for certain lines of code

- packages/docs-article-templates/package.json
- packages/docs-article-templates/src/test/suite/controllers/quick-pick-controller.test.ts
- packages/docs-article-templates/src/test/suite/extension.test.ts
- yarn.lock
[AB#458010](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/458010)
> Security fixes

- package-lock.json
- packages/docs-markdown/package.json
- packages/docs-markdown/src/helper/utility.ts
- packages/docs-markdown/src/test/suite/controllers/quick-pick-menu-controller.test.ts
- packages/docs-markdown/src/test/suite/helper/metadata-completion.test.ts
- packages/docs-markdown/src/test/test.common/common.ts
- packages/docs-metadata/.gitignore
- packages/docs-metadata/package.json
We now successfully have the OneBranch pipeline configuired for the .Net core apps for docs-metadata. This change just changes the download URL to the new location.
> 445489 onebranch migration

- packages/docs-images/package.json
- packages/docs-images/src/test/suite/extension.test.ts
Fixed build for extension context type
> Fixed VSCode Extension Context Type
