authoring-extension/package.json

Adding conditions to keybindings.  If vscodevim is installed and active, do not use our keybindings.

Partial incompatibility with vscodevim extension

---

authoring-extension/package-lock.json
authoring-extension/package.json

Was just reading through the code and VS Code was complaining that it couldn't figure out the typings after I did npm install.
Most of the lock file changes were actually caused by my initial `npm install`, but I'll call those out inline.

build: Add typings for node-dir

---

authoring-extension/src/controllers/quick-pick-menu-controller.ts
authoring-extension/src/controllers/template-controller.ts
authoring-extension/src/extension.ts
authoring-extension/src/helper/common.ts

1. [quick-pick-menu-controller] Move quick pick options and item array to the beginning of the markdownQuickPick function.  This was done to build out the quickpick list prior to showing the dropdown (check for dependent extensions).
2. [quick-pick-menu-controller] Start writing errors/helpful info to the output window instead of console for user awareness.
3. [template-controller] Added template-controller to call the applyTemplate command if the extension is installed.
4. [common] Add function to gather datetime information for timestamps.
5. [extension] Create function to create an output channel for the docs-markdown extension on load.

Integrate template extension into docs-markdown

---

docs-preview/src/server.ts

The root cause is that only parent process (cmd.exe) has been killed, and this PR is to spawn markdocs service directly then issue will be resolved.

Fix markdocs service can't be killed

---

docs-preview/src/server.ts

Reverts Microsoft/vscode-docs-authoring#72
Mistakenly merged.  We have an error with await being used in a non-async function.
{
"resource": "/d:/GitHub/vscode-docs-authoring/docs-preview/src/server.ts",
"owner": "typescript",
"code": "1308",
"severity": 8,
"message": "'await' expression is only allowed within an async function.",
"source": "ts",
"startLineNumber": 74,
"startColumn": 28,
"endLineNumber": 74,
"endColumn": 33
}

Revert "Fix bug while stopping markdocs server"

---

docs-preview/package-lock.json
docs-preview/package.json
docs-preview/src/server.ts
docs-preview/src/util/platformInforamtion.ts

Reduce the size of runtime dependency([mardocs-server](https://github.com/qinezh/markdocs-server/releases)) from around 25MB to 732KB if user has already installed .NET Core runtime in Windows/Linux/macOS.

Reduce size of dependency

---

docs-markdown/changelog.md
docs-markdown/package-lock.json
docs-markdown/package.json

1. Remove markdownQuickPick command from navigation menu.
2. Update version and changelog.
3. Remove redundant octicons dependency and update mocha to resolve security vulnerabilities.
Resolves issue:
https://github.com/Microsoft/vscode-docs-authoring/issues/82

remove quickpick from navigation menu

---

docs-markdown/src/controllers/master-redirect-controller.ts
docs-markdown/src/extension.ts

Link-ui-changes branch contains structure changes due to refactoring and the changes in the master-redirect-updates branch were made based on that structure.  Figured going into link-ui branch with a smaller number of changes would be easier to review.
1. Additional information in notification pop-up.
2. Single output window stream (docs-markdown-master-redirect) with verbose logging.
3. Better error-handling with json interactions.
4. Improved filter logic to reduce the number of files that are parsed.
5. New function to standardize messaging.

Merge master redirect updates into link ui branch

---

docs-markdown/changelog.md

I think I only noticed this pushed out today, but used the date from 80d61a7ea481774aa1e9ad5e4d85f89667807d47

chore: Update Changelog date for docs-markdown

---

docs-markdown/changelog.md
docs-markdown/package-lock.json
docs-markdown/package.json
docs-markdown/src/controllers/bookmark-controller.ts
docs-markdown/src/controllers/media-controller.ts
docs-markdown/src/helper/ui.ts

1. Add new function to add external and internal link options to toolbar link command
2. Change bookmark/heading command to support h2-h6 (no more h1)
Resolves issue [94](https://github.com/Microsoft/vscode-docs-authoring/issues/94)

Update toolbar link options and heading level support

---

docs-markdown/src/controllers/master-redirect-controller.ts

1. Removed redirect_document_id hardcoded 'false' value.
1. Updated logic to check for a valid yaml header and redirect_url attribute.  If this check passes, then check for the redirect_document_id attribute.
**Expected results for redirect_document_id attribute**
If present and true: value is true
If present and false: value is false
If redirect_document_id attribute is not present: value is false
If redirect_document_id attribute is present but value is empty: value is false

Improve handling of redirect_document_id Boolean

---

docs-markdown/package-lock.json
docs-markdown/package.json

> docs-markdown@0.1.6 postinstall D:\GitHub\vscode-docs-authoring\docs-markdown
> node ./node_modules/vscode/bin/install
Detected VS Code engine version: ^1.22.0
Found minimal version that qualifies engine range: 1.22.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/6b4d53cdab8bcae1eaaa4934d93c077319b573db/src/vs/vscode.d.ts
vscode.d.ts successfully installed!
audited 969 packages in 3.9s
found 2 high severity vulnerabilities
run `npm audit fix` to fix them, or `npm audit` for details
PS D:\GitHub\vscode-docs-authoring\docs-markdown> npm audit fix
+ vscode@1.1.21
added 10 packages from 13 contributors, removed 18 packages, updated 40 packages and moved 9 packages in 4.121s
fixed 2 of 2 vulnerabilities in 969 scanned packages
PS …

Fix vulnerabilities in docs-markdown

---

docs-markdown/package.json
docs-markdown/src/extension.ts
docs-markdown/test/extension.test.ts
docs-markdown/test/helper/format-styles.test.ts
docs-markdown/test/index.ts
docs-markdown/test/resources/testStrings.ts

1. Update **npm run test** to run full test suite (both core extension functionality and custom linting rules.
1. Add new test command, **test-core**, to run unit tests for 'native' extension functionality.
1. Move generateTimestamp function to within extension.ts functions to unblock core extension unit tests.
1. Fix linting errors in core extension unit tests.
Testing
1. Pull latest code and checkout jamarw/run-full-test-suite branch.
1. Open terminal and navigate to docs-markdown directory in local clone.
1. Run **npm-install**.
1. Run **npm run vscode:prepublish** to compile code.
1. Run **npm run test-rules** (this command should launch four unit tests for markdownlint custom rules).
1. Run **npm run test-core** (this command should launch 23 unit tests for core extension …

Update unit test suite

---

docs-article-templates/src/controllers/quick-pick-controller.ts
docs-article-templates/src/helper/github.ts
docs-article-templates/src/helper/unit-builder.ts
docs-article-templates/src/strings.ts

1. Use map data sctructure to store file and path data.
2. Populate quickpick with map keys (friendly/file names).
3. Linting cleanup.

Add support for friendly template names

---

docs-yaml/package-lock.json
docs-yaml/package.json

Resolving 3 vulnerabilities found after running `npm install`.
audited 862 packages in 4.642s
found 3 vulnerabilities (2 low, 1 moderate)
run `npm audit fix` to fix them, or `npm audit` for details

Fix vulnerabilities

---

docs-article-templates/src/controllers/quick-pick-controller.ts
docs-article-templates/src/helper/unit-builder.ts
docs-article-templates/src/strings.ts

1. Add conditional quickpick option to  push new unit option to menu if a module file is active/open.  If a user has a module file open (index.yml), a new quickpick option (Add module to unit) will show in the menu.
2. Create new function to handle updating existing modules.  Code will determine if the module already exists or if it's a new module.  If the module exists, the addModuleToUnit function will be called.  This will read the module data, use the existing values, create the new units and update the associated index.yml file.  If it's a new module, there existing functionality remains the same.
3. Remove unused async declarations.

Add units to existing module

---

docs-article-templates/src/helper/unit-builder.ts

Found a scenario where optional metadata can be overwritten when a new unit is created.  To prevent overwrites, the code was updated to notify the user instead of automatically updating the module (index.yml). Automatic-updating will be implemented once another solution is found.
1. Add optional preserveValues parameter to cleanupUnit function.
2. Add condition that will notify the user that the index file will need to be updated if a unit was added to an existing module.  New modules and units creation will not change.
3. Remove additional unit prompt from addUnitToModule function.

Preserve values when adding a unit

---

docs-preview/.gitignore
docs-preview/.vscode/launch.json
docs-preview/.vscode/settings.json
docs-preview/.vscode/tasks.json
docs-preview/README.md
docs-preview/changelog.md
docs-preview/package-lock.json
docs-preview/package.json
docs-preview/src/extension.ts

1. Add vscode settings to enable local debugging
2. Update vscode version
3. Add changelog and update readme
4. Update extension.ts to use VSCode preview instead of docs-preview environment

Add local debugging and prep for 0.3.17 release

---

docs-yaml/CHANGELOG.md
docs-yaml/README.md
docs-yaml/package-lock.json
docs-yaml/package.json

Removing broken links in readme that are unnecessary because the information is already available on the [marketplace](https://marketplace.visualstudio.com/items?itemName=docsmsft.docs-yaml).

Remove unnecessary links in readme

---

docs-markdown/changelog.md
docs-markdown/package-lock.json
docs-markdown/package.json
docs-markdown/src/controllers/list-controller.ts
docs-markdown/src/helper/list.ts

Support custom tab sizes in lists. Extension does not check for tabSize settings and defaults to 4 spaces. This PR will check for editor.tabSize setting and allow the user to either use that value or continue to use the supported 4 space pattern.
**List-controller.ts**
1. Instead of calling insertList function, it now calls evaluateIndent
**Lists.ts**
1. getTabSize function: Checks for the editor.tabSize setting and returns the value
2. evaluateIndent function: Checks to see if editor.tabSize value is supported. If not, calls indentationMessage function to notify the user.
3. indentationMessage function: Notify the user if tab size is unsupported and provide an option to use default value or unsupported custom value.
4. createIndent function: Create the tabPattern (spaces) based on the …

Support custom tab sizes in lists

---

docs-markdown/changelog.md
docs-markdown/package.json
docs-markdown/src/controllers/list-controller.ts
docs-markdown/src/helper/list.ts

Breaking change in latest VS Code release.  Address this [issue](https://github.com/microsoft/vscode-docs-authoring/issues/232).
1. Remove setting.
2. Update version and changelog.
3. Remove custom setting code.

Remove custom tabbing support

---

docs-markdown/src/controllers/cleanup-controller.ts

Seems to follow, since you have a markdownlint rule to flag them https://github.com/microsoft/vscode-docs-authoring/blob/22f34877bc93904603faa770be07a462a3e5f173/docs-markdown/markdownlint-custom-rules/common.js#L43

feat(cleanup): Re-write flagged Microsoft links to HTTPS

---

docs-preview/changelog.md
docs-preview/package-lock.json
docs-preview/package.json

Add conditions to only show preview commands for markdown files.

Only show preview commands for markdown

---

docs-article-templates/CHANGELOG.md
docs-article-templates/package-lock.json
docs-article-templates/package.json
docs-article-templates/src/helper/github.ts

**User feedback/requests**
1) In the vscode logs, output the url and the http response. 
2) Share the URL where the templates reside so we can trace/troubleshoot. 
3) The ability to download the templates for offline use.
**Updates**
1. Add new function to log repo data (show url, response code and local template directory path).

Docs-article-templates public feedback

---

docs-markdown/README.md
docs-markdown/changelog.md
docs-markdown/package-lock.json
docs-markdown/package.json
docs-markdown/src/controllers/yaml-controller.ts

1. Removing maintainContext and items attributes from `TOC entry with optional attributes` command.
2. Bump version, changelog and update readme.

Update optional TOC attributes

---

docs-markdown/changelog.md
docs-markdown/src/controllers/yaml-controller.ts

1. Get the toc.yml file path and determine the relative file path to the selected href topic.
2. Format href path and add to TOC instead of using selected file name.

TOC href target in different directory

---

docs-markdown/changelog.md
docs-markdown/src/controllers/yaml-controller.ts

1. Moved template strings into position if statements.
2. Use cursor position to determine indent instead of relying on fixed spacing.

Fix nested toc attribute line-up error

---

docs-markdown/changelog.md
docs-markdown/src/controllers/quick-pick-menu-controller.ts

Update logic to use VS Code language detection instead of using the file extension.  Both .yml and .yaml files should show quickpick options.

Update quickpick to use language identifier instead of file extension

---

docs-preview/src/markdown-extensions/codesnippet.ts
docs-preview/src/markdown-extensions/includes.ts

Add tilde regex to includes.ts and codesnippet.ts 
- used to replace **~** with the repo root path so the include/snippet source file can be read
- updated path is not written back to the markdown file and surrounding text is not affected

Support tilde in file path preview

---

docs-markdown/src/controllers/cleanup-controller.ts

These now get flagged by OpenBuild, but aren't cleaned up by the controller

feat: cleanup go.microsoft.com links

---

docs-authoring-pack/CHANGELOG.md
docs-authoring-pack/package-lock.json
docs-authoring-pack/package.json
docs-authoring-pack/readme.md

Testing steps:
* Uninstall docs-authoring-pack and all dependencies
* pull branch
* create package: run `vsce package` in `docs-authoring-pack` folder
* install packaged vsix
* verify all dependent extensions are installed, including blackmist.LinkCheckMD

add blackmist.LinkCheckMD to DAP

---

docs-markdown/markdownlint-custom-rules/common.js
docs-markdown/markdownlint-custom-rules/image.js

If image type is **content** or **complex**, check for required alt-text attribute.  Resolves issue with unsupported types returning alt-text required.

Image linting alt-text required for unsupported attribute

---

docs-markdown/package-lock.json
docs-markdown/package.json
docs-markdown/src/controllers/include-controller.ts

Update include command to use glob for pattern matching.  Only markdown files in **includes** directories should be displayed in the quickpick menu.

Filter for items in includes folders when inserting includes

---

docs-images/CHANGELOG.md
docs-images/package.json

Hi @meganbradley and @IEvangelist , the publishing step failed earlier because the extension version was the same as the published version so this is just a quick PR to update the versioning for deployment.  Thanks

Bump docs-images version

---

docs-markdown/package-lock.json
docs-markdown/package.json
docs-markdown/src/controllers/include-controller.ts

I was experiencing a bug where markdown files were not being displayed in the quick selection list when using the <kbd>F1</kbd> Docs: Include functionality. The issue is that the glob pattern didn't account for files potentially nested under an includes directory. For example, prior to this change the only markdown files displayed in the quick selection would be the `include-file.md` whereas, I was expected all the markdown files under the includes directory.
```
└── includes
├── subfolder
│    ├── sub-file-01.md
│    └── sub-file-02.md
└── include-file.md
```
With this change, all of these markdown files are displayed.

Fixed a bug where directories under include folders were not found

---

docs-markdown/.vscode/settings.json
docs-markdown/package.json
docs-markdown/src/controllers/metadata-controller.ts
docs-markdown/src/extension.ts
docs-markdown/src/helper/common.ts
docs-markdown/src/helper/utility.ts

I added the ability to right-click within a markdown file and update the `ms.date` value to the current date. This will save me and hopefully many others a lot of time in the future. Here is an example of it in action:
Notice the date value now. Right-click in markdown file, select "Update "ms.date" Metadata Value" option
Now observe the updated date.
I also cleaned up a few minor things that observed while exploring the code.

Added markdown context menu item to "Update ms.date Metadata Value"

---

docs-markdown/package.json
docs-markdown/src/controllers/link-controller.ts
docs-markdown/src/controllers/media-controller.ts
docs-markdown/src/controllers/quick-pick-menu-controller.ts
docs-markdown/src/helper/common.ts
docs-markdown/src/helper/utility.ts

I have added the ability to insert links from yaml files. This is HUGELY helpful with links that we create in `index.yml` and `toc.yml` files. Today we do not have support in place for this functionality. Here is an example of it working...

Added the ability to insert links from yaml files.

---

docs-markdown/package.json
docs-markdown/src/controllers/sort-controller.ts
docs-markdown/src/extension.ts

I added the ability to sort selections, either ascending or descending. This is helpful to ensure that certain things are sorted correctly and useful for tables, in fact the reason I created this is due to the manual difficulty I was having when trying to sort language and locale tables for Speech service docs. I really could have used this feature then :smile:.
> **Note:** the menu item is only ever available when the editor has a selection.
When testing this locally, feel free to use this markdown -- or any other variation.
```markdown
| Letter | Details |
|--------|---------|
| Z | The last letter in the alphabet |
| C | The a letter after A in the alphabet |
| X | The alphabet letter is towards the end |
| M | Somewhere in the middle? |
| A | The first letter in the …
```

Added the ability to sort selections: asc or desc.

---

docs-markdown/package.json
docs-markdown/src/controllers/metadata-controller.ts
docs-markdown/tsconfig.json

I've got another nice-to-have feature that will hopefully help to increase content development productivity. I just wanted to add a note here explaining how appreciative I am of this amazing platform, for being so accepting of contributions and supportive. I feels great to collaborate on these kinds of things!
See details below:
Watch this short GIF, that demonstrates this new functionality. Notice the various metadata values, such as the `titleSuffix`, `author`, `manager`, `ms.service`, `ms.subservice`, `ms.date` and `ms.author`. All of these values are discoverable in the workspace `docfx.json` if specified. If they are not found there, the `author` and `ms.author` are pulled from the templates config. What this means, is that for repos that have configured implicit …

Added implicit metadata updates

---

docs-markdown/package.json
docs-markdown/src/helper/highlight-langs.ts

The `dotnetcli` dev lang was missing. Adding it in this PR and setting as popular so that it appears in the triple-tick autocomplete dialog. This dev lang is used extensively across multiple doc sets. Example: https://docs.microsoft.com/aspnet/core/client-side/libman/libman-cli?view=aspnetcore-3.1#installation

Add .NET Core CLI dev lang to highlight languages list

---

docs-markdown/package.json
docs-markdown/src/controllers/master-redirect-controller.ts
docs-markdown/src/controllers/metadata-controller.ts
docs-markdown/src/helper/common.ts

Added the ability to sort the `.openpublishing.redirection.json` file. Open the command pallet and quickly sort the entire file alphabetically.

Added sorting of the master redirect file.

---

docs-markdown/.vscode/settings.json
docs-markdown/package.json
docs-markdown/src/controllers/table-controller.ts
docs-markdown/src/helper/markdown-table.ts
docs-markdown/tsconfig.json

I added the ability to format a selected markdown table. This will evenly distribute the tables columns making it more readable and at a glance more clearly indicate the number of columns, etc. This feature correctly maintains both the column alignment and table position indentation.

Added right-click, automatic formatting of markdown tables.

---

README.md
docs-authoring-pack/readme.md

Clean up markdown readme file, but also fix an issue where the image is not rendered on the marketplace.

Corrected missing image when shown in the VS Code marketplace.

---

docs-markdown/src/helper/highlight-langs.ts

Fix the invalid formatting in the tooltip:
With this PR, the "Output:" heading displays as follows:

Fix formatting in dev lang tooltip heading

---

docs-markdown/package.json
docs-markdown/src/controllers/metadata-controller.ts
docs-markdown/src/extension.ts
docs-markdown/src/helper/utility.ts

Here is a feature that I believe will be super impactful. It will automatically replace smart quotes in MD files. There is a very common workflow where PMs provide Word docs with content and if authors copy & paste, this leads to MD files being littered with undesirable characters. Here is a quick demo of this feature in action (of course backed by a configuration making it optional).
When `true`, automatically replace smart quotes (`“, ”, ‘, and ’`) such as those found in Word documents - with standard quotes (`" and '`) in markdown files.

Added the ability to replace smart quotes in markdown files.

---

docs-markdown/src/helper/highlight-langs.ts

Swap the position of 2 words so that the resulting message makes more sense.

Swap ordering of wording in invalid devlang message

---

docs-markdown/src/controllers/media-controller.ts

This PR supports two scenarios for repo links:
1. **No selected text**: H1 from linked topic is used as link text.
2. **Selected text**: Selected text is used as link text.

Remove alt text prompt for repo links

---

docs-markdown/package.json
docs-markdown/src/controllers/metadata-controller.ts

I wanted to use some of the update metadata commands now for a while in YAML, as they are the same in terms of replacing matched `RegExp` in the `metadata-controller.ts` logic. This pull request does enables it for YAML now too.

Expanded the usage of the update metadata values command to YAML

---

docs-markdown/src/helper/utility.ts

Issue referenced by #470. Small bug fix to include double quote when user selects Id snippet type.

Fixed bug with code snippet id.

---

docs-markdown/package.json
docs-markdown/src/controllers/master-redirect-controller.ts
docs-markdown/src/test/suite/controllers/master-redirect-controller.test.ts

This pull request adds the ability for daisy chains to be resolved in the *.openpublishing.redirection.json* file automatically. This details of this feature were initially discussed here as [considerations](https://docs.microsoft.com/en-us/contribute/docs-authoring/sort-redirects#considerations).
Below is a before and after scenario, to demonstrate the goal of this functionality.
```json
{
"redirections": [
{
"source_path": "articles/subject/a.md",
"redirect_url": "/azure/subject/b",
"redirect_document_id": false
},
{
"source_path": "articles/subject/b.md",
"redirect_url": "/azure/subject/c?query-string#bookmark",
"redirect_document_id": false
},
{
"source_path": "articles/subject/c.md",
"redirect_url": "/azure/subject/d?pivot=example",
"redirect_document_id": true
},
{
"source_path": …
```

Implemented daisy chain resolution

---

docs-markdown/package-lock.json
docs-markdown/src/controllers/bold-controller.ts
docs-markdown/src/controllers/bookmark-controller.ts
docs-markdown/src/controllers/code-controller.ts
docs-markdown/src/controllers/include-controller.ts
docs-markdown/src/controllers/italic-controller.ts
docs-markdown/src/controllers/list-controller.ts
docs-markdown/src/controllers/master-redirect-controller.ts
docs-markdown/src/controllers/media-controller.ts
docs-markdown/src/controllers/no-loc-controller.ts
docs-markdown/src/controllers/quick-pick-menu-controller.ts
docs-markdown/src/controllers/row-columns-controller.ts
docs-markdown/src/controllers/table-controller.ts
docs-markdown/src/controllers/xref-controller.ts
docs-markdown/src/controllers/yaml-controller.ts

**Updates made to address the following rules**:
- ordered-imports           Named imports must be alphabetized.
- ordered-imports           Import sources within a group must be alphabetized.
- prefer-const              Identifier 'selections' is never reassigned; use 'const' instead of 'let'.
- triple-equals             == should be ===
- only-arrow-functions      non-arrow functions are forbidden
- no-shadowed-variable      Shadowed name: 'files'
- comment-format            comment must start with a space
- no-empty                  block is empty
- radix                     Missing radix parameter
**Affected controllers**:
- Bold
- Bookmark
- Code
- Include
- Italic
- List
- Master-redirect
- Media
- No-loc
- Quick-pick
- Row-column
- Table
- Xref
- Yaml

TSLint fixes

---

docs-linting/src/controllers/lint-config-controller.ts
docs-linting/src/extension.ts

TSLint fixes for rules below:
- Unnecessarily quoted property 'front_matter_title' found.
- Forbidden 'var' keyword, use 'let' or 'const' instead
- Comment must start with a space
- Parentheses are required around the parameters of an arrow function definition

Docs-linting TSLint fixes

---

docs-article-templates/package.json

We probably do not want the extension to fire always, we probably only want it to be active when user opens a markdown or yaml document?

Updated activation events for docs article templates.

---

docs-markdown/src/controllers/cleanup/remove-unused-assets-controller.ts

**Include** references that don't contain a space are deleted because the include regex expects one.  This PR allows for an optional space after the opening **include**.
The **esql-md.md** references in this [file ](https://github.com/dotnet/docs/blob/master/docs/framework/data/adonet/ef/entityclient-provider-for-the-entity-framework.md)are examples of the erroneous deletions .  This PR will make these references valid entries and the cleanup command will not flag **esql-md.md** for deletion.

Update include regex in unused asset removal command

---

docs-markdown/package.json
docs-markdown/src/ICommand.ts
docs-markdown/src/controllers/link-controller.ts
docs-markdown/src/extension.ts
docs-markdown/src/helper/highlight-langs.ts
docs-markdown/src/helper/utility.ts

Added collapse relative links functionality. Inspired by pull requests such as this:
- https://github.com/dotnet/docs/pull/18461
- https://github.com/dotnet/docs/pull/18471
- https://github.com/dotnet/docs/pull/18472
- https://github.com/dotnet/docs/pull/18497
- etc...
Automate this functionality with the click of a button, I hope that @NextTurn will appreciate this addition 🎉 
Validated the following link examples:
```markdown
[Link 1](http://microsoft.com)
[Link 2](https://microsoft.com)
[Link 3](link.md)
[Link 4](/link.md)
[Link 5](./link.md)
[Link 6](../link.md)
[Link 7](~/link.md)
[Link 8](../../link.md?q=1)
[Link 9](../../link.md#bookmark)
[Link 10](../../../link.md?q=1#bookmark)
```
Using this JavaScript RegExp:
```typescript
linkRegExp: RegExp = …
```

Added collapse relative links functionality

---

docs-markdown/package.json
docs-markdown/src/controllers/link-controller.ts
docs-markdown/src/extension.ts
docs-markdown/src/test/data/repo/articles/link-controller.md
docs-markdown/src/test/data/repo/articles/subdir/sub-link-controller.md
docs-markdown/src/test/suite/controllers/italic-controller.test.ts
docs-markdown/src/test/suite/controllers/link-controller.test.ts

Added the ability to call "Collapse relative links in folder" from the explorer context menu. Also, cleanup lint violations from recent merges.

Collapse in folder

---

docs-markdown/package.json
docs-markdown/src/controllers/redirects/daisyChainResolution.ts
docs-markdown/src/controllers/redirects/generateRedirectionFile.ts
docs-markdown/src/controllers/redirects/redirect-url.ts
docs-markdown/src/controllers/redirects/redirection.ts
docs-markdown/src/controllers/redirects/removeDefaultJsonValues.ts
docs-markdown/src/controllers/redirects/removeInvalidRedirectDocIds.ts
docs-markdown/src/controllers/redirects/sortRedirects.ts
docs-markdown/src/controllers/redirects/utilities.ts

The source_path value was deleted from .openpublishing.redirection.json when the redirection script was run.  This PR fixes that issue.  Updated the activation events to include json files.

Fix master redirect command

---

docs-markdown/package.json

Docs-markdown shouldn't override `Tab` in snippets.

Add new condition to insertNestedList command

---

docs-linting/changelog.md
docs-linting/package.json
docs-markdown/changelog.md
docs-markdown/package.json
docs-preview/changelog.md
docs-preview/package.json

Production Release for docs-markdown, docs-preview, and docs-linting
docs-markdown:
- Added support for triple colon video extension insertion.
- Bug fix for Link in repo.
- Updated collapse relative link feature.
docs-preview:
- Added triple colon video extension support.
- Bug fix for preview refresh on xref and codesnippet extensions.
docs-linting:
- Added more moniker linting
- Added video extension linting

Production Release for docs-markdown, docs-preview, and docs-linting

---

docs-images/CHANGELOG.md
docs-images/package.json

Updated package.json and changelog. Changes include:
- Upgrade dependency versions
- Import from es and enable interop
- Add timeout with delay to prevent hangs
- Do not use arithmetic coding with JPG compression
- Added mime-type validation to ensure that the file type is actually the same as the assumed type from the file extension

docs-images production release

---

docs-linting/markdownlint-custom-rules/common.js

This is a small change to add ``notes`` to the list of supported Markdown extensions.
This should resolve the issue noted in #583.

Update Markdown extensions list

---

docs-preview/changelog.md
docs-preview/package-lock.json
docs-preview/package.json

Release fix for issue [672](https://github.com/microsoft/vscode-docs-authoring/issues/672)

Docs-preview release 0.3.53

---

docs-markdown/package.json
docs-markdown/src/controllers/cleanup/devlangsInCodeBlocks.ts
docs-markdown/src/test/suite/controllers/quick-pick-menu-controller.test.ts
docs-markdown/src/test/suite/helper/metadata-completion.test.ts
docs-markdown/src/test/test.common/common.ts

This PR fixes the following errors and updates VSCode engine and types to the latest version:

Add extension mode property and bump vscode version

---

docs-markdown/package.json
docs-markdown/src/controllers/notebook-controller.ts
docs-markdown/src/controllers/quick-pick-menu-controller.ts
docs-markdown/src/extension.ts
docs-markdown/src/helper/common.ts
docs-markdown/src/test/suite/controllers/notebook-controller.test.ts

Authors: [Sheri Gilley](@sdgilley) & [David Pine](@IEvangelist)
Insert the markdown version of a Jupyter notebook from GitHub into a document.  When the notebook content changes, you can quickly update that markdown.
There are two commands added to the command palette:
* **Docs: Insert Jupyter notebook** - enter the URL of the notebook.  A markdown version of the notebook is added to the document starting at the position of your cursor.  Do not modify the start or end tags; it's what the next function uses to update the notebook.  
* **Docs: Update Jupyter notebook** in the start tag, re-read the notebook and replace the contents between start and end with the latest version.  If you insert multiple notebooks in the same document (why would you do that?) only the first one will be …

Hackathon project - Insert / update Jupyter notebook from GitHub

---

docs-preview/src/helper/common.ts
docs-preview/src/seo/seoHelpers.ts
docs-preview/src/test/suite/seo/seoHelpers.test.ts

Fixed issue where SEO preview was not able to pull docfx and breadcrumb file.
Issue #679 has been fixed. And tested with referral.md to check if the md file would render the SEO Preview.
Issue had to do with breadcrumb file not being found and terminating the renderer early. Breadcrumb was looking for a yaml file but docfx was pointing to toc.json. Now handling this case. 
[AB#265722](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/265722)

Fixed issue where SEO preview was not able to pull docfx and breadcrumb file.

---

docs-markdown/src/helper/bookmark-builder.ts

In germany we have bookmarks which contain german special characters like ä,ö,ü,ß.
These are perfectly fine for markdown or html. But currently these are deleted while generating the link through the "Add Link" Feature. This leads to broken links in our markdown file and currently we fix these broken links manually by adding the characters again.

Fix links with german characters

---

docs-preview/src/helper/common.ts
docs-preview/src/markdown-extensions/codesnippet.ts
docs-preview/src/markdown-extensions/column.ts
docs-preview/src/markdown-extensions/image.ts
docs-preview/src/markdown-extensions/includes.ts
docs-preview/src/markdown-extensions/rootDirectory.ts
docs-preview/src/markdown-extensions/xref.ts

Docs-preview is creating multiple output channels.  We only need the channel created in extension.ts so this PR removes the additional channel spun up in common.ts.

Remove output channel from common

---

docs-preview/src/extension.ts
docs-preview/src/helper/common.ts
docs-preview/src/markdown-extensions/codesnippet.ts
docs-preview/src/markdown-extensions/column.ts
docs-preview/src/markdown-extensions/image.ts
docs-preview/src/markdown-extensions/includes.ts
docs-preview/src/markdown-extensions/rootDirectory.ts
docs-preview/src/markdown-extensions/xref.ts
docs-preview/src/test/suite/markdown-extensions/image.test.ts

Added image extension for inline blocks. Triple Colon Images now work inline with other text and render fine without having their own line. [AB#272927](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/272927)

Added image extension for inline blocks

---

packages/docs-preview/media/wrapper.js

Wrapper.js is ignored so it doesn't look like it moved with the husky changes.
Here's an older [branch](https://github.com/microsoft/vscode-docs-authoring/tree/279111_AllowlistProxy/docs-preview/media) with wrapper.js for reference.

Adding wrapper.js

---

packages/docs-markdown/src/controllers/quick-pick-menu-controller.ts

Remove Command Description text in quick pick menu.
[AB#284457](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/284457)

Remove Command Description text in quick pick menu

---

yarn.lock

Diff after a fresh clone and `yarn install`

chore: Renerate yarn.lock

---

packages/docs-markdown/changelog.md
packages/docs-markdown/package.json

Changes for docs-markdown release 0.2.81 include:
- Validation extension integration.
- Updated devlangs to include X++.
- Removed quick pick command descriptions.
- Added no-loc unit tests.

docs-markdown production release version 0.2.81

---

packages/docs-preview/README.md

Preview setting image didn't appear because link was broken. Previous link contained the "full path" (https://raw.githubusercontent...) so I kept it that way, probably needed while rendered on MS Marketplace and places like that.  
Very nice package BTW! 👍

Fix broken Preview image link after repo reorg

---

packages/docs-markdown/src/controllers/metadata-controller.ts
packages/docs-markdown/src/helper/common.ts
packages/docs-markdown/src/helper/metadata.ts
packages/docs-markdown/src/test/suite/controllers/metadata-controller.test.ts

Issue where metadata date nag was notifying users that command only works on markdown document fixed to no longer notify users.

Fixed issue where metadata date nag is prompting markdown message when saving on all documents

---

packages/docs-markdown/changelog.md
packages/docs-markdown/package.json

- Fixed bug with add period to alt text not running on cleanup
- Fixed bug with metadata date nag running on all files and notifying user that command only works on markdown file

docs-markdown release 0.2.84

---

packages/docs-markdown/src/controllers/links/linkToDocsPageByUrl.ts
packages/docs-markdown/src/test/suite/controllers/cleanup/cleanup-controller.test.ts
packages/docs-markdown/src/test/suite/controllers/image-controller.test.ts

Now supporting content subsets defined in the docfx.json file.
- Searching if content exists in docfx.json
- matching both link path, current file path with docfx src. 
[AB#386119](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/386119)

Support content subsets defined in docfx.json

---

packages/docs-markdown/changelog.md
packages/docs-markdown/package.json

- Added functionality for formatting markdown table as data matrix using right click context menu when table is selected.

docs-markdown production release 0.2.86

---

packages/docs-markdown/src/controllers/image-controller.ts
packages/docs-markdown/src/test/data/repo/articles/image-controller6.md
packages/docs-markdown/src/test/suite/controllers/image-controller.test.ts

Addressed issue where if the :::image::: tag had a comman (,) in the alt-text if would not register as an :::image::: tag. This issue has been fixed for this PR on all the inserting functionality like loc-scope, link, and lightbox.
[AB#420613](https://dev.azure.com/ceapex/d3d54af3-265a-4f18-95f6-9a46397ca583/_workitems/edit/420613)

Fixed regex for lightbox insert.

---

packages/docs-metadata/package.json
packages/docs-metadata/src/test/suite/extension.test.ts
yarn.lock

Remove unused file-system dependency to fix security issue with utils-extend

Remove unused file-system dependency from docs-metadata

---

packages/docs-authoring-pack/package.json

- docs-visual-areas is causing slow downs on various user machines. Rolling back to previous version. Unfortunately I believe users will have to uninstall docs-visual-areas for the issues to go away until the problem is resolved with the docs-visual-areas extension.

Removing docs-visual-areas as it is causing issues

---

packages/docs-markdown/src/controllers/metadata/metadata-controller.ts
packages/docs-markdown/src/extension.ts

Metadata Explorer was no longer refreshing automatically either when you opened a different Markdown file or when you closed the active file.
Changing to this event also fixes the error that pops up when you start typing a new metadata key in the YAML front matter.

Fix metadata refresh functionality

---

packages/docs-markdown/changelog.md
packages/docs-markdown/package.json

- Small update the metadata tree view onchange event.

docs-markdown release 0.2.97
